export const products = [
          {
            id: 1,
            title: "Barphi",
            description: "Tastyy",
            price: "500",
            img: "./images/Barphi.jpg",
            quantity: 1,
          },
          {
            id: 2,
            title: "Butter",
            description: "wow amazing",
            price: "200",
            img: "./images/butter.jpg",
            quantity: 1,
          },
          {
            id: 3,
            title: "Icecream",
            description: "Sweet and cool",
            price: "300",
            img: "./images/Icecream.jpg",
            quantity: 1,
          },
          {
            id: 4,
            title: "Milk",
            description: "Best milk ever",
            price: "100",
            img: "./images/Milk.webp",
            quantity: 1,
          },
          {
            id: 5,
            title: "Rasgulla",
            description: "white in color",
            price: "250",
            img: "./images/Rasgulla.jpg",
            quantity: 1,
          },
          {
            id: 6,
            title: "cheese",
            description: "yellow in color",
            price: "1500",
            img: "./images/cheese.jpg",
            quantity: 1,
          },
          {
            id: 7,
            title: "Yogurt",
            description: "black in color",
            price: "500",
            img: "./images/Yogurt.jpg",
            quantity: 1,
          },
          {
            id: 8,
            title: "Paneer",
            description: "Best quality ever",
            price: "90500",
            img: "./images/Paneer.jpeg",
            quantity: 1,
          },
          {
            id: 9,
            title: "Mixed Sweets",
            description: "black in color",
            price: "2500",
            img: "./images/Mixed-sweet.png",
            quantity: 1,
          },
        ];